# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
#https://juejin.cn/post/6866766361218482189
#https://www.jianshu.com/p/5727a39e8c79
#https://stackoverflow.com/questions/76590131/error-while-build-ios-app-in-xcode-sandbox-rsync-samba-13105-deny1-file-w
target 'StudyAsynDisplay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudyAsynDisplay
  pod 'AsyncDisplayKit', :path => 'LocalLib/AsyncDisplayKit'
  pod 'ObjCRuntimeUtils', :path => 'LocalLib/ObjCRuntimeUtils'
  pod 'SwiftSignalKit', :path => 'LocalLib/SwiftSignalKit'
  pod 'Markdown', :path => 'LocalLib/Markdown'
  pod 'AppBundle', :path => 'LocalLib/AppBundle'
  pod 'UIKitRuntimeUtils', :path => 'LocalLib/UIKitRuntimeUtils'
  pod 'Display', :path => 'LocalLib/Display'

  target 'StudyAsynDisplayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudyAsynDisplayUITests' do
    # Pods for testing
  end

end
