# Uncomment the next line to define a global platform for your project
# Specs satisfying the `ffmpeg-kit-ios-full (= 6.0), ffmpeg-kit-ios-full` dependency were found, but they required a higher minimum deployment target.
# platform :ios, '12.0'变platform :ios, '13.0'，再改回12.0
install! 'cocoapods', :disable_input_output_paths => true
platform :ios, '12.0'
 ## https://juejin.cn/post/6866766361218482189
 ## https://www.jianshu.com/p/5727a39e8c79
 ## https://stackoverflow.com/questions/76590131/error-while-build-ios-app-in-xcode-sandbox-rsync-samba-13105-deny1-file-w
target 'StudyAsynDisplay' do
 ## Comment the next line if you don't want to use dynamic frameworks
 ##  use_frameworks!
use_frameworks! :linkage => :static

  ## Pods for StudyAsynDisplay
  pod 'AsyncDisplayKit', :path => 'LocalLib/AsyncDisplayKit'
  pod 'ObjCRuntimeUtils', :path => 'LocalLib/ObjCRuntimeUtils'
  pod 'SwiftSignalKit', :path => 'LocalLib/SwiftSignalKit'
  pod 'Markdown', :path => 'LocalLib/Markdown'
  pod 'AppBundle', :path => 'LocalLib/AppBundle'
  pod 'UIKitRuntimeUtils', :path => 'LocalLib/UIKitRuntimeUtils'
  pod 'Display', :path => 'LocalLib/Display'
  ## 使用ListView引入
  pod 'MergeLists', :path => 'LocalLib/MergeLists'
  
  ## 使用ItemListUI引入
  pod 'ItemListUI', :path => 'LocalLib/ItemListUI'
  pod 'TelegramAnimatedStickerNode', :path => 'LocalLib/TelegramAnimatedStickerNode'
  ## pod 'SwiftSignalKit', :path => 'LocalLib/SwiftSignalKit'
  ## pod 'Display', :path => 'LocalLib/Display'
  pod "TelegramPresentationData", :path => 'LocalLib/TelegramPresentationData'
  ## pod 'MergeLists', :path => 'LocalLib/MergeLists'
  pod "TextFormat", :path => 'LocalLib/TextFormat'
  ## pod "Markdown", :path => 'LocalLib/Markdown'
  pod "ProgressNavigationButtonNode", :path => 'LocalLib/ProgressNavigationButtonNode'
  pod "SwitchNode", :path => 'LocalLib/SwitchNode'
  pod "AnimatedStickerNode", :path => 'LocalLib/AnimatedStickerNode'
  pod "TelegramAnimatedStickerNode", :path => 'LocalLib/TelegramAnimatedStickerNode'
  pod "CheckNode", :path => 'LocalLib/CheckNode'
  pod "SegmentedControlNode", :path => 'LocalLib/SegmentedControlNode'
  pod "AccountContext", :path => 'LocalLib/AccountContext'
  pod "AnimationUI", :path => 'LocalLib/AnimationUI'
  pod "ShimmerEffect", :path => 'LocalLib/ShimmerEffect'
  pod "ManagedAnimationNode", :path => 'LocalLib/ManagedAnimationNode'
  pod "AvatarNode", :path => 'LocalLib/AvatarNode'
  pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  
  ## TelegramPresentationData依赖引入
  ##  pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  pod "Postbox", :path => 'LocalLib/Postbox'
  ##  pod "Display", :path => 'LocalLib/Display'
  ##  pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
  pod "TelegramUIPreferences", :path => 'LocalLib/TelegramUIPreferences'
  pod "MediaResources", :path => 'LocalLib/MediaResources'
  ##  pod "AppBundle", :path => 'LocalLib/AppBundle'
  pod "StringPluralization", :path => 'LocalLib/StringPluralization'
  pod "Sunrise", :path => 'LocalLib/Sunrise'
  pod "TinyThumbnail", :path => 'LocalLib/TinyThumbnail'
  pod "FastBlur", :path => 'LocalLib/FastBlur'
  ## 从生成的内容里同步的 /private/var/tmp/_bazel_flow/77a9618ad4b516ed2b48d93fb9fb04ab/rules_xcodeproj.noindex/build_output_base/execroot/__main__/bazel-out/ios-sim_arm64-min12.0-applebin_ios-ios_sim_arm64-dbg-ST-9bca64169500/bin/Telegram/GeneratedPresentationStrings
  pod "PresentationStrings", :path => 'LocalLib/GeneratedPresentationStrings'
  
  ## TelegramCore依赖引入
  pod "TelegramApi", :path => 'LocalLib/TelegramApi'
  pod "MtProtoKit", :path => 'LocalLib/MtProtoKit'
  pod "CloudData", :path => 'LocalLib/CloudData'
  pod "EncryptionProvider", :path => 'LocalLib/EncryptionProvider'
  pod "CryptoUtils", :path => 'LocalLib/CryptoUtils'
  pod "NetworkLogging", :path => 'LocalLib/NetworkLogging'
  pod "Reachability", :path => 'LocalLib/Reachability'
  pod "ManagedFile", :path => 'LocalLib/ManagedFile'
  pod "RangeSet", :path => 'LocalLib/RangeSet'
  pod "DarwinDirStat", :path => 'LocalLib/DarwinDirStat'
  pod "Emoji", :path => 'LocalLib/Emoji'
  
  ## Postbox依赖引入
  pod "Crc32", :path => 'LocalLib/Crc32'
  pod "sqlcipher", :path => 'LocalLib/sqlcipher'
  pod "MurMurHash32", :path => 'LocalLib/MurMurHash32'
  pod "StringTransliteration", :path => 'LocalLib/StringTransliteration'
  
  ## TextFormat依赖引入
  ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  ## pod "Display", :path => 'LocalLib/Display'
  ## pod "TelegramPresentationData", :path => 'LocalLib/TelegramPresentationData'
  ## pod "Markdown", :path => 'LocalLib/Markdown'
  ## pod "Emoji", :path => 'LocalLib/Emoji'

  ## ProgressNavigationButtonNode依赖引入
  ## pod "Display", :path => 'LocalLib/Display'
  ## pod "AsyncDisplayKit", :path => 'LocalLib/AsyncDisplayKit'
  pod "ActivityIndicator", :path => 'LocalLib/ActivityIndicator'
  
  ## SwitchNode依赖引入
  ## pod "AsyncDisplayKit", :path => 'LocalLib/AsyncDisplayKit'
  ## pod "Display", :path => 'LocalLib/Display'
    pod "LegacyComponents", :path => 'LocalLib/LegacyComponents'
    
  ## AnimatedStickerNode依赖引入
  ## pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
  ## pod "AsyncDisplayKit", :path => 'LocalLib/AsyncDisplayKit'
  ## pod "Display", :path => 'LocalLib/Display'
    pod "YuvConversion", :path => 'LocalLib/YuvConversion'
    pod "GZip", :path => 'LocalLib/GZip'
    pod "RLottieBinding", :path => 'LocalLib/rlottie'
    pod "MediaResources", :path => 'LocalLib/MediaResources'
    pod "UniversalMediaPlayer", :path => 'LocalLib/MediaPlayer'
  ## od "ManagedFile", :path => 'LocalLib/ManagedFile'
  ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
    pod "AnimationCompression", :path => 'LocalLib/AnimationCompression'
    pod "MetalImageView", :path => 'LocalLib/MetalImageView'
    pod "WebPBinding", :path => 'LocalLib/WebPBinding'
    
    ## TelegramAnimatedStickerNode依赖引入
    ## pod "Postbox", :path => 'LocalLib/Postbox'
    ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
      pod "StickerResources", :path => 'LocalLib/StickerResources'
  ## pod "MediaResources", :path => 'LocalLib/MediaResources'
      pod "LocalMediaResources", :path => 'LocalLib/LocalMediaResources'
      pod "Tuples", :path => 'LocalLib/Tuples'
  ## pod "AnimatedStickerNode", :path => 'LocalLib/AnimatedStickerNode'
  ## pod "RLottieBinding", :path => 'LocalLib/rlottie'
  ## pod "YuvConversion", :path => 'LocalLib/YuvConversion'
  ## pod "GZip", :path => 'LocalLib/GZip'
  ## pod "ManagedFile", :path => 'LocalLib/ManagedFile'
  ## pod "UniversalMediaPlayer", :path => 'LocalLib/MediaPlayer'
      pod "SoftwareVideo", :path => 'LocalLib/SoftwareVideo'
  ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'

  ## AccountContext依赖引入
  ##  pod "TelegramAudio", :path => 'LocalLib/TelegramAudio'
  ##  pod "AsyncDisplayKit", :path => 'LocalLib/AsyncDisplayKit'
   pod "TemporaryCachedPeerDataManager", :path => 'LocalLib/TemporaryCachedPeerDataManager'
   pod "DeviceLocationManager", :path => 'LocalLib/DeviceLocationManager'
  ##  pod "UniversalMediaPlayer", :path => 'LocalLib/MediaPlayer'
  ##  pod "TelegramPresentationData", :path => 'LocalLib/TelegramPresentationData'
  ##  pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
  ##  pod "Postbox", :path => 'LocalLib/Postbox'
  ##  pod "TelegramCore", :path => 'LocalLib/TelegramCore'
   pod "MusicAlbumArtResources", :path => 'LocalLib/MusicAlbumArtResources'
  ##  pod "RangeSet", :path => 'LocalLib/RangeSet'
   pod "InAppPurchaseManager", :path => 'LocalLib/InAppPurchaseManager'
  ##  pod "TextFormat", :path => 'LocalLib/TextFormat'
   pod "AnimationCache", :path => 'LocalLib/TelegramUI/Components/AnimationCache'
   pod "MultiAnimationRenderer", :path => 'LocalLib/TelegramUI/Components/MultiAnimationRenderer'
  
  ## StringPluralization依赖引入
  pod "NumberPluralizationForm", :path => 'LocalLib/NumberPluralizationForm'
  
  ## LegacyComponents依赖引入
  pod 'SSignalKit', :path => 'LocalLib/SSignalKit'
  ##  pod "AppBundle", :path => 'LocalLib/AppBundle'

  ## ShimmerEffect引入
  ## pod 'AsyncDisplayKit', :path => 'LocalLib/AsyncDisplayKit'
  ## pod 'Display', :path => 'LocalLib/Display'
  pod 'HierarchyTrackingLayer', :path => 'LocalLib/Components/HierarchyTrackingLayer'
  pod 'GenerateStickerPlaceholderImage', :path => 'LocalLib/TelegramUI/Components/Utils/GenerateStickerPlaceholderImage'

  ## AnimationCompression引入
  pod "DctHuffman", :path => 'LocalLib/AnimationCompression/DctHuffman'
  pod 'MetalImageView', :path => 'LocalLib/MetalImageView'

  ## UniversalMediaPlayer引入
  ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  ## pod 'Postbox', :path => 'LocalLib/Postbox'
  ## pod 'SwiftSignalKit', :path => 'LocalLib/SwiftSignalKit'
  ## pod 'AsyncDisplayKit', :path => 'LocalLib/AsyncDisplayKit'
  ## pod 'Display', :path => 'LocalLib/Display'
  pod 'TelegramAudio', :path => 'LocalLib/TelegramAudio'
  pod 'FFMpegBinding', :path => 'LocalLib/FFMpegBinding'
  pod 'RingBuffer', :path => 'LocalLib/RingBuffer'
  ## pod 'YuvConversion', :path => 'LocalLib/YuvConversion'
  ## pod 'RangeSet', :path => 'LocalLib/RangeSet'
  ## pod 'TextFormat', :path => 'LocalLib/TextFormat'
  
  ## WebPBinding引入
  pod "webp", :path => 'LocalLib/webp'
  
  ## StickerResources引入
  ##  pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  ##  pod "Postbox", :path => 'LocalLib/Postbox'
  ##  pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
  ##  pod "Display", :path => 'LocalLib/Display'
  pod "ImageBlur", :path => 'LocalLib/ImageBlur'
  ##  pod "Tuples", :path => 'LocalLib/Tuples'
  ##  pod "MediaResources", :path => 'LocalLib/MediaResources'
  ##  pod "TelegramUIPreferences", :path => 'LocalLib/TelegramUIPreferences'
  ##  pod "WebPBinding", :path => 'LocalLib/WebPBinding'
  
 ## AnimationUI引入
 ## pod "AsyncDisplayKit", :path => 'LocalLib/AsyncDisplayKit'
 ## pod "RLottieBinding", :path => 'LocalLib/rlottie'
 pod "Lottie", :path => 'LocalLib/lottie-ios'
 ## pod "GZip", :path => 'LocalLib/GZip'
 ## pod "AppBundle", :path => 'LocalLib/AppBundle'
 ## pod "Display", :path => 'LocalLib/Display'
 
 ## LocalMediaResources引入
 ## pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
 ## pod "Postbox", :path => 'LocalLib/Postbox'
 ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
   pod "ImageCompression", :path => 'LocalLib/ImageCompression'
   pod "PersistentStringHash", :path => 'LocalLib/PersistentStringHash'
   
   ## Reachability引入
   ## pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
  pod "LegacyReachability", :path => 'LocalLib/Reachability/LegacyReachability'
  
  ## ImageCompression引入
  pod "MozjpegBinding", :path => 'LocalLib/MozjpegBinding'
  
  ## AvatarNode引入
  ## pod "AsyncDisplayKit", :path => 'LocalLib/AsyncDisplayKit'
  ## pod "Display", :path => 'LocalLib/Display'
  ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  ## pod "Postbox", :path => 'LocalLib/Postbox'
  ## pod "TelegramPresentationData", :path => 'LocalLib/TelegramPresentationData'
  ## pod "AnimationUI", :path => 'LocalLib/AnimationUI'
  ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  ## pod "AppBundle", :path => 'LocalLib/AppBundle'
  ## pod "AccountContext", :path => 'LocalLib/AccountContext'
  ## pod "Emoji", :path => 'LocalLib/Emoji'
  ## pod "TinyThumbnail", :path => 'LocalLib/TinyThumbnail'
  ## pod "FastBlur", :path => 'LocalLib/FastBlur'
  pod "ComponentFlow", :path => 'LocalLib/ComponentFlow'
  pod "AvatarStoryIndicatorComponent", :path => 'LocalLib/TelegramUI/Stories/AvatarStoryIndicatorComponent'
  pod "DirectMediaImageCache", :path => 'LocalLib/DirectMediaImageCache'

  ## MusicAlbumArtResources 引入
  ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  ## pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
  pod "UrlEscaping", :path => 'LocalLib/UrlEscaping'

  ## TemporaryCachedPeerDataManager 引入
  pod "TelegramStringFormatting", :path => 'LocalLib/TelegramStringFormatting'
  ## pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
  ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  ## pod "Postbox", :path => 'LocalLib/Postbox'

  ## TelegramStringFormatting 引入
  ## pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  ## pod "Display", :path => 'LocalLib/Display'
  pod "PlatformRestrictionMatching", :path => 'LocalLib/PlatformRestrictionMatching'
  pod "LocalizedPeerData", :path => 'LocalLib/LocalizedPeerData'
  ## pod "TextFormat", :path => 'LocalLib/TextFormat'
  ## pod "Markdown", :path => 'LocalLib/Markdown'
  ## pod "TelegramUIPreferences", :path => 'LocalLib/TelegramUIPreferences'
  ## pod "TelegramPresentationData", :path => 'LocalLib/TelegramPresentationData'
  ## pod "AppBundle", :path => 'LocalLib/AppBundle'

  ## AnimationCache 引入
  ## pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
  ## pod "CryptoUtils", :path => 'LocalLib/CryptoUtils'
  ## pod "ManagedFile", :path => 'LocalLib/ManagedFile'
  pod "ImageDCT", :path => 'LocalLib/TelegramUI/Components/AnimationCache/ImageDCT'
  ## 暂时只引入图片声音等资源文件
  pod "TelegramUI", :path => 'LocalLib/TelegramUI'
  
  ## MozjpegBinding引入
  pod "mozjpeg", :path => 'LocalLib/mozjpeg'
  pod "jxl", :path => 'LocalLib/libjxl'

## PresentationDataUtils 引入
  pod "PresentationDataUtils", :path => 'LocalLib/PresentationDataUtils'
## pod "Display", :path => 'LocalLib/Display'
## pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
## pod "AccountContext", :path => 'LocalLib/AccountContext'
## pod "TelegramPresentationData", :path => 'LocalLib/TelegramPresentationData'
  pod "AlertUI", :path => 'LocalLib/AlertUI'
##  pod "ItemListUI", :path => 'LocalLib/ItemListUI'
  pod "SolidRoundedButtonNode", :path => 'LocalLib/SolidRoundedButtonNode'
  pod "OverlayStatusController", :path => 'LocalLib/OverlayStatusController'
  pod "OverlayStatusControllerImpl", :path => 'LocalLib/OverlayStatusController/Impl'
  pod "UrlWhitelist", :path => 'LocalLib/UrlWhitelist'

## AlertUI引入
##  pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
##  pod "AsyncDisplayKit", :path => 'LocalLib/AsyncDisplayKit'
##  pod "Display", :path => 'LocalLib/Display'
  pod "TextNodeWithEntities", :path => 'LocalLib/TelegramUI/Components/TextNodeWithEntities'
 
## TextNodeWithEntities引入
##  pod "SwiftSignalKit", :path => 'LocalLib/SwiftSignalKit'
##  pod "AsyncDisplayKit", :path => 'LocalLib/AsyncDisplayKit'
##  pod "Display", :path => 'LocalLib/Display'
##  pod "TextFormat", :path => 'LocalLib/TextFormat'
  pod "EmojiTextAttachmentView", :path => 'LocalLib/TelegramUI/Components/EmojiTextAttachmentView'
##  pod "AnimationCache", :path => 'LocalLib/TelegramUI/Components/AnimationCache'
##  pod "MultiAnimationRenderer", :path => 'LocalLib/TelegramUI/Components/MultiAnimationRenderer'
  pod "InvisibleInkDustNode", :path => 'LocalLib/InvisibleInkDustNode'

## EmojiTextAttachmentView引入
  pod "LottieAnimationCache", :path => 'LocalLib/TelegramUI/Components/LottieAnimationCache'
  pod "VideoAnimationCache", :path => 'LocalLib/TelegramUI/Components/VideoAnimationCache'

  
  ###======== 待解决问题 ============
  # libjxl+mozjpeg+webp, 需要自动生成，目前是使用了模拟器生成的内容
  # FFMpegBinding引入，ffmpeg改为ffmpeg-kit-ios-full代替
  # pod "ffmpeg", :path => 'LocalLib/ffmpeg'
  pod 'ffmpeg-kit-ios-full', '= 6.0'
  
  ## 三方库
  pod 'GDPerformanceView-Swift'
  pod 'SnapKit'
  pod 'Kingfisher'

  target 'StudyAsynDisplayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudyAsynDisplayUITests' do
    # Pods for testing
  end

end
