# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
#https://juejin.cn/post/6866766361218482189
#https://www.jianshu.com/p/5727a39e8c79
#https://stackoverflow.com/questions/76590131/error-while-build-ios-app-in-xcode-sandbox-rsync-samba-13105-deny1-file-w
target 'StudyAsynDisplay' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  use_frameworks! :linkage => :static

  # Pods for StudyAsynDisplay
  pod 'AsyncDisplayKit', :path => 'LocalLib/AsyncDisplayKit'
  pod 'ObjCRuntimeUtils', :path => 'LocalLib/ObjCRuntimeUtils'
  pod 'SwiftSignalKit', :path => 'LocalLib/SwiftSignalKit'
  pod 'Markdown', :path => 'LocalLib/Markdown'
  pod 'AppBundle', :path => 'LocalLib/AppBundle'
  pod 'UIKitRuntimeUtils', :path => 'LocalLib/UIKitRuntimeUtils'
  pod 'Display', :path => 'LocalLib/Display'
  pod 'AuthorizationUtils', :path => 'LocalLib/AuthorizationUtils'
  pod 'libphonenumber', :path => 'LocalLib/libphonenumber'
  pod 'PhoneNumberFormat', :path => 'LocalLib/PhoneNumberFormat'
  pod 'PhoneInputNode', :path => 'LocalLib/PhoneInputNode'
#  pod 'CountrySelectionUI', :path => 'LocalLib/CountrySelectionUI'
  pod 'YuvConversion', :path => 'LocalLib/YuvConversion'
  pod 'GZip', :path => 'LocalLib/GZip'
  pod 'ManagedFile', :path => 'LocalLib/ManagedFile'
  pod 'MetalImageView', :path => 'LocalLib/MetalImageView'
  pod "MediaResources", :path => 'LocalLib/MediaResources'
  pod "UniversalMediaPlayer", :path => 'LocalLib/MediaPlayer'
  pod "TelegramCore", :path => 'LocalLib/TelegramCore'
  pod "AnimationCompression", :path => 'LocalLib/AnimationCompression'
  pod "WebPBinding", :path => 'LocalLib/WebPBinding'
  pod "webp", :path => 'LocalLib/webp'
  pod 'AnimatedStickerNode', :path => 'LocalLib/AnimatedStickerNode'
  pod 'StickerResources', :path => 'LocalLib/StickerResources'
  pod 'ImageBlur', :path => 'LocalLib/ImageBlur'
  pod 'Tuples', :path => 'LocalLib/Tuples'
  pod 'LocalMediaResources', :path => 'LocalLib/LocalMediaResources'
  
  pod 'mozjpeg', :path => 'LocalLib/mozjpeg'
  pod 'jxl', :path => 'LocalLib/libjxl'
  pod 'MozjpegBinding', :path => 'LocalLib/MozjpegBinding'
  
  pod 'ImageCompression', :path => 'LocalLib/ImageCompression'
  pod 'PersistentStringHash', :path => 'LocalLib/PersistentStringHash'
  pod 'SoftwareVideo', :path => 'LocalLib/SoftwareVideo'
  
  
  pod 'TelegramAnimatedStickerNode', :path => 'LocalLib/TelegramAnimatedStickerNode'
  pod "RangeSet", :path => 'LocalLib/RangeSet'
  pod "DarwinDirStat", :path => 'LocalLib/DarwinDirStat'
  pod "CryptoUtils", :path => 'LocalLib/CryptoUtils'
  pod "Crc32", :path => 'LocalLib/Crc32'
  pod "sqlcipher", :path => 'LocalLib/sqlcipher'
  pod "MurMurHash32", :path => 'LocalLib/MurMurHash32'
  pod "StringTransliteration", :path => 'LocalLib/StringTransliteration'
  pod "Postbox", :path => 'LocalLib/Postbox'
  pod "TelegramUIPreferences", :path => 'LocalLib/TelegramUIPreferences'
  pod "Emoji", :path => 'LocalLib/Emoji'
  pod "EncryptionProvider", :path => 'LocalLib/EncryptionProvider'
  pod "Reachability", :path => 'LocalLib/Reachability'
  pod "LegacyReachability", :path => 'LocalLib/Reachability/LegacyReachability'
  pod "NetworkLogging", :path => 'LocalLib/NetworkLogging'
  pod "MtProtoKit", :path => 'LocalLib/MtProtoKit'
  pod "TelegramApi", :path => 'LocalLib/TelegramApi'
  pod "CloudData", :path => 'LocalLib/CloudData'
  pod "AnimationCompression", :path => 'LocalLib/AnimationCompression'
  pod "DctHuffman", :path => 'LocalLib/AnimationCompression/DctHuffman'
  pod "TextFormat", :path => 'LocalLib/TextFormat'
  pod "TelegramPresentationData", :path => 'LocalLib/TelegramPresentationData'
  pod "PresentationStrings", :path => 'LocalLib/GeneratedPresentationStrings'
  pod "TelegramAudio", :path => 'LocalLib/TelegramAudio'
  pod "FFMpegBinding", :path => 'LocalLib/FFMpegBinding'
#  pod "ffmpeg", :path => 'LocalLib/ffmpeg'
  pod 'ffmpeg-kit-ios-full'
  pod "RingBuffer", :path => 'LocalLib/RingBuffer'
  pod "StringPluralization", :path => 'LocalLib/StringPluralization'
  pod "NumberPluralizationForm", :path => 'LocalLib/NumberPluralizationForm'
  pod "Sunrise", :path => 'LocalLib/Sunrise'
  pod "TinyThumbnail", :path => 'LocalLib/TinyThumbnail'
  pod "FastBlur", :path => 'LocalLib/FastBlur'
   pod "RLottieBinding", :path => 'LocalLib/rlottie'
  pod "TelegramStringFormatting", :path => 'LocalLib/TelegramStringFormatting'
  pod "LocalizedPeerData", :path => 'LocalLib/LocalizedPeerData'
  pod "PlatformRestrictionMatching", :path => 'LocalLib/PlatformRestrictionMatching'
#  pod "SearchBarNode", :path => 'LocalLib/SearchBarNode'
  pod "ActivityIndicator", :path => 'LocalLib/ActivityIndicator'
#  pod "AvatarNode", :path => 'LocalLib/AvatarNode'

  target 'StudyAsynDisplayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudyAsynDisplayUITests' do
    # Pods for testing
  end

end
